[package]
name = "libcpdf-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
thiserror = "1.0.57"
libc = "0.2.153"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
reqwest = { version = "0.11.25" }
tokio = { version = "1", features = ["full"] }
